# Generated by Django 5.0.6 on 2024-06-26 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='langchainpgcollection',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='langchainpgembedding',
            options={'managed': True},
        ),
    ]
