# Generated by Django 5.0.6 on 2024-06-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_langchainpgcollection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='langchainpgcollection',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='langchainpgembedding',
            options={'managed': False},
        ),
    ]
