# Generated by Django 5.0.6 on 2024-07-10 20:29

import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_langchainpgcollection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=255)),
                ('is_student', models.BooleanField(default=True)),
                ('top_result', models.CharField(max_length=255)),
                ('search_timestamp', models.DateTimeField(auto_now_add=True)),
                ('embedding', pgvector.django.VectorField(dimensions=1536)),
            ],
        ),
    ]
